### ISSUE TITLE
El bot no se conecta a los canales de voz

### ISSUE THREAD

**Issue by ColukD** [rodrigorioo/coscu-bot#10]
![Screenshot_2](https://user-images.githubusercontent.com/74360714/98943453-49813700-24ce-11eb-899e-0612c3ad9b7b.png)

Ayer cuando apenas ingreso al canal andaba, pero luego de un rato dejo de andar

**Comment by rodrigorioo** [comment]
Hola @ColukD, acabo de subir el fix de este bug que reportaron muchos.

Disculpa por la demora.
