### ISSUE TITLE
No se conecta a los canales de voz (20/4/2020)

### ISSUE THREAD

**Issue by ImNexon** [rodrigorioo/coscu-bot#2]
![image](https://user-images.githubusercontent.com/64037230/79786906-82807100-831c-11ea-90a1-4dc988908d9a.png)

Por más que escribamos el comando el Bot no se conecta a ningún canal de voz.

**Comment by rodrigorioo** [comment]
Hola, al meter el bot le diste los permisos para que pueda ver los canales? O te fijaste que dentro del servidor el rol que tiene asignado le permita entrar a los chanels?

En general si no entra al servidor es por un tema de permisos

**Comment by ImNexon** [comment]
Buenos días, con el rol que trae por defecto no debería poder conectarse? De todas maneras dándole otro rol con permisos tampoco se conecta

**Comment by rodrigorioo** [comment]
Probaste sacándolo y volviéndolo a meter? En todos los chanels pasa lo mismo?

**Comment by ImNexon** [comment]
Sip, lo he expulsado del servidor y metido de nuevo, también probé modo automático y manual. 
En todos los channels igual

**Comment by ImNexon** [comment]
21/4/2020 16:02
Actualización: El bot empezó a andar sin haber hecho ningún cambio por mi lado, gracias por tu tiempo.

**Comment by rodrigorioo** [comment]
Buenísimo! La verdad no se por que pasó ese error pero genial que se resolvió
