### ISSUE TITLE
El bot ingresa al canal pero no reproduce la voz

### ISSUE THREAD

**Issue by Ivan147852** [rodrigorioo/coscu-bot#3]
Hola! El código compila, pero al escribir el comando, el bot entra al canal y no habla. La instrucción que está fallando es la del dispatcher.play, luego del voicechannel.join, me sale el mensaje de que revise los permisos del canal, pero eso lo checkee con:

if(mensaje.guild.me.hasPermission("SPEAK")){
            console.log("Tiene permiso para hablar");
        }
        else{
            console.log("No tiene permiso para hablar");
        }
}
y el bot tiene permisos, no pude encontrar la solución online, no sé si me podrás ayudar. De antemano, muchas gracias!

**Comment by rodrigorioo** [comment]
Hola, seguramente te falte FFmpeg: http://blog.gregzaal.com/how-to-install-ffmpeg-on-windows/

**Comment by Ivan147852** [comment]
Muchísimas gracias por contestar. Luego de añadir al path FFmpeg, seguía sin funcionarme (había tenido problemas instalando el node-opus), el opusscript (alternativo a node-opus). Mil gracias, espectacular tu trabajo!
