### ISSUE TITLE
No esta andando

### ISSUE THREAD

**Issue by cesardmoro** [rodrigorioo/coscu-bot#4]
No esta andando el bot ahora, aparece desconectado de los servers  
![image](https://user-images.githubusercontent.com/8697604/86845937-95375600-c080-11ea-8240-a7b772704267.png)

**Comment by Chulusca** [comment]
Me pasa lo mismo

**Comment by rodrigorioo** [comment]
Duplicate of #5

**Comment by rodrigorioo** [comment]
@cesardmoro le agregue el sharding asi que ya está on nuevamente
