### ISSUE TITLE
El bot esta offline

### ISSUE THREAD

**Issue by Chulusca** [rodrigorioo/coscu-bot#5]
El bot esta offline no lee los mensajes ni hace nada, ??

**Comment by rodrigorioo** [comment]
Hola, Discord me obliga a refactorizar todo el código y cambiarle la arquitectura porque llegó a los 2500 svs. Dejo el link de lo que habría que hacer: https://discordjs.guide/sharding/

**Comment by rodrigorioo** [comment]
@Chulusca le agregue el sharding asi que ya está on nuevamente
