### ISSUE TITLE
Bot no se conecta a los canales despues de desconectarlo

### ISSUE THREAD

**Issue by Patvis** [rodrigorioo/coscu-bot#9]
Uno de los audios era medio largo y lo pusieron en medio de un clutch de CSGO... cuestión que desconecté al bot del canal en el que estaba sonando (sin kickearlo ni nada) y ahora cuando ponemos comandos me responde que se agrega a la fila el sonido pero no entra a decirlo :(
Probé lo siguiente:
-Cambiar modos a automatico y devuelta a manual
-Crear roles con permisos especificos para que se vea el canal de voz que quiero que entre (por defecto ya los tenia)
-Kickear al bot del server y volver a invitarlo
-Banear al bor del server y volver a invitarlo

**Comment by PAJ4R0** [comment]
Me pasa igual, y no se como arreglarlo ya, no sos el unico.

**Comment by rodrigorioo** [comment]
Hola, @PAJ4R0 @Patvis acabo de subir un update que soluciona este problema.

Perdón por la demora en corregirlo.
